<?php

namespace Savannabits\Saas\Filament\Pages;

use DanHarrin\LivewireRateLimiting\Exceptions\TooManyRequestsException;
use Filament\Forms\Components\Component;
use Filament\Forms\Components\TextInput;
use Filament\Forms\Form;
use Filament\Http\Responses\Auth\Contracts\LoginResponse;
use Filament\Notifications\Notification;
use Filament\Pages\Auth\Login as BaseLogin;
use Illuminate\Contracts\Support\Htmlable;
use Illuminate\Support\Facades\Config;
use Illuminate\Support\Facades\Log;
use Illuminate\Validation\ValidationException;
use LdapRecord\Laravel\Auth\ListensForLdapBindFailure;
use Savannabits\Saas\Services\Users;

class Login extends BaseLogin
{
    use ListensForLdapBindFailure;
    protected static ?string $navigationIcon = 'heroicon-o-document-text';

    protected static string $view = 'savannabits-saas::pages.auth.login';

    public function mount(): void
    {
        parent::mount(); // TODO: Change the autogenerated stub
    }

    public function getHeading(): string | Htmlable
    {
        return 'University Login';
    }

    public function getSubheading(): string | Htmlable | null
    {
        return 'Use your university AD credentials to login';
    }

    public function authenticate(): ?LoginResponse
    {
        try {
            $this->rateLimit(5);
        } catch (TooManyRequestsException $exception) {
            Notification::make()
                ->title(__('filament-panels::pages/auth/login.notifications.throttled.title', [
                    'seconds' => $exception->secondsUntilAvailable,
                    'minutes' => ceil($exception->secondsUntilAvailable / 60),
                ]))
                ->body(array_key_exists('body', __('filament-panels::pages/auth/login.notifications.throttled') ?: []) ? __('filament-panels::pages/auth/login.notifications.throttled.body', [
                    'seconds' => $exception->secondsUntilAvailable,
                    'minutes' => ceil($exception->secondsUntilAvailable / 60),
                ]) : null)
                ->danger()
                ->send();

            return null;
        }

        $data = $this->form->getState();
        $provider = is_numeric($data['username']) ? 'students' : 'staff';

        // Ensure the user exists or synchronize the user
        $user = \App\Models\User::whereUsername($data['username'])->first();
        if (! $user) {
            try {
                $user = Users::make()->syncUser($data['username'], $provider);
            } catch (\Throwable $exception) {
                Log::error($exception);
                Notification::make('error')->danger()->body($exception->getMessage())->title('User Sync Error')->persistent()->send();
            }
        }

        Config::set('auth.guards.web.provider', $provider);
        $userProvider = \Auth::createUserProvider($provider);
        \Auth::setProvider($userProvider);
        $this->listenForLdapBindFailure();
        $res = \Auth::attempt($this->getCredentialsFromFormData($data), $data['remember'] ?? false);
        if (! $res) {
            throw ValidationException::withMessages([
                'data.username' => __('filament-panels::pages/auth/login.messages.failed'),
            ]);
        }
        Log::info('Login passed');
        session()->regenerate();

        return app(LoginResponse::class);
    }

    public function form(Form $form): Form
    {
        return $form
            ->schema([
                $this->getUsernameFormComponent(),
                $this->getPasswordFormComponent(),
                $this->getRememberFormComponent(),
            ])
            ->statePath('data');
    }

    protected function getPasswordFormComponent(): Component
    {
        return TextInput::make('password')
            ->label(__('filament-panels::pages/auth/login.form.password.label'))
//            ->hint(filament()->hasPasswordReset() ? new HtmlString(Blade::render('<x-filament::link :href="filament()->getRequestPasswordResetUrl()"> {{ __(\'filament-panels::pages/auth/login.actions.request_password_reset.label\') }}</x-filament::link>')) : null)
            ->password()
            ->required();
    }

    protected function getUsernameFormComponent(): Component
    {
        return TextInput::make('username')
            ->label(__('Username'))
            ->required()
            ->autocomplete('username')
            ->autofocus();
    }

    protected function getCredentialsFromFormData(array $data): array
    {
        return [
            'samaccountname' => $data['username'],
            'password' => $data['password'],
            /*'fallback' => [
                'username' => $data['username'],
                'password' => $data['password']
            ]*/
        ];
    }
    protected function throwLoginValidationException(string $message): void
    {
        throw ValidationException::withMessages([
            'data.username' => "$message",
        ]);
    }
}
